name: Tests
# ejecuta las pruebas unitarias (variante runTests, que omite las pruebas que se sabe que fallan)

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - '*.gradle*'
      - 'gradle/**'
  pull_request:
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew testRunTestsUnitTest

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
